# Generated by Django 3.2.6 on 2021-08-09 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('x', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('y', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('temperature', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
