# Generated by Django 3.2.6 on 2021-08-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='available',
        ),
    ]
